config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get  '/about',   to: 'static_pages#about'
  get  'static_pages/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  'static_pages/contact', to: 'static_pages#contact'

  get '/sign_in', to: 'users#sign_in'

  resources :homegroups do
    resources :items
  end

  resources :invites

  devise_for :users, controllers: { sessions: 'users/sessions' }

  root to: 'static_pages#about'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/homegroup.rb
class Homegroup < ApplicationRecord
  has_many :homegroup_users
  has_many :users, through: :homegroup_users
  has_many :items
  has_many :invites
  validates :name, presence: true

end

app/models/homegroup_user.rb
class HomegroupUser < ApplicationRecord
  belongs_to :homegroup
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :homegroup
  attr_accessor :homegroup_id
  validates :item_name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :homegroup_users
  has_many :homegroups, through: :homegroup_users
  has_many :invitations, :class_name => "Invite", :foreign_key => 'recipient_id'
  has_many :sent_invites, :class_name => "Invite", :foreign_key => 'sender_id'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, :only => [:about, :contact]

end

app/controllers/homegroups_controller.rb
class HomegroupsController < ApplicationController
  before_action :set_homegroup, only: [:show, :edit, :update]


  # GET /homegroups
  # GET /homegroups.json
  def index
    @homegroups = current_user.homegroups.all
  end

  # GET /homegroups/1
  # GET /homegroups/1.json
  def show
    @homegroup = Homegroup.find(params[:id])
    @invite = @homegroup.invites.build
  end

  # GET /homegroups/new
  # not sure about the .new part
  def new
    @homegroup = current_user.homegroups.new
  end

  # GET /homegroups/1/edit
  def edit
    @homegroup = Homegroup.find(params[:id])

  end

  # POST /homegroups
  # POST /homegroups.json
  def create
    def homegroup_params
      params.require(:homegroup).permit(:name)
    end
    @homegroup = current_user.homegroups.create(homegroup_params)


    respond_to do |format|
      if @homegroup.save
        format.html { redirect_to @homegroup, notice: 'Homegroup was successfully created.' }
        format.json { render :show, status: :created, location: @homegroup }
      else
        format.html { render :new }
        format.json { render json: @homegroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homegroups/1
  # PATCH/PUT /homegroups/1.json
  def update
    def homegroup_params
      params.require(:homegroup).permit(:name)
    end
    respond_to do |format|
      if @homegroup.update(homegroup_params)
        format.html { redirect_to @homegroup, notice: 'Homegroup was successfully updated.' }
        format.json { render :show, status: :ok, location: @homegroup }
      else
        format.html { render :edit }
        format.json { render json: @homegroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homegroups/1
  # DELETE /homegroups/1.json
  def destroy
    @homegroup.destroy
    respond_to do |format|
      format.html { redirect_to homegroups_url, notice: 'Homegroup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homegroup
      @homegroup = Homegroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homegroup_params
      params.require(:homegroup).permit(:index, :show)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_filter :load_homegroup, except: [:destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = @homegroup.items.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @homegroup = Homegroup.find(params[:homegroup_id])
    @item = @homegroup.items.create(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @homegroup, notice: 'Item was successfully created.' }
        # format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @homegroup = @item.homegroup
    @item.destroy

    # @item = @homegroup.items.find(item_params)
    @item.destroy
    respond_to do |format|
      format.html { redirect_to homegroup_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:item_name, :homegroup_id)
    end

    def load_homegroup
      @homegroup = Homegroup.find(params[:homegroup_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title = '')
    base_title = "GroceryList"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/homegroups_helper.rb
module HomegroupsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/homegroups/_form.html.erb
<%= form_for(@homegroup) do |f| %>
  <% if homegroup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(homegroup.errors.count, "error") %> prohibited this homegroup from being saved:</h2>

      <ul>
      <% homegroup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homegroups/edit.html.erb
<% provide(:title, "Edit #{@homegroup.name}") %>

<h1>Editing Homegroup</h1>

<%= render 'form', homegroup: @homegroup %>

<%= link_to 'Back', @homegroup %>

app/views/homegroups/index.html.erb
<% provide(:title, "Homegroups") %>
<h1>Homegroups</h1>

<table>
  <thead>
    <tr>
      <th>Index</th>
      <th>Show</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homegroups.each do |homegroup| %>
      <tr>

        <td><%= homegroup.name %></td>
        <td><%= link_to 'Show', homegroup %></td>
        <td><%= link_to 'Edit', edit_homegroup_path(homegroup) %></td>
        <td><%= link_to 'Delete', homegroup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Homegroup', new_homegroup_path %>

app/views/homegroups/new.html.erb
<% provide(:title, "Create Homegroup") %>

<h1>New Homegroup</h1>

<%= render 'form', homegroup: @homegroup %>

<%= link_to 'Back', homegroups_path %>

app/views/homegroups/show.html.erb
<% provide(:title, "#{@homegroup.name}") %>
<h1>Grocery List for Homegroup: <%= @homegroup.name %>
          </h1>
          <h2><%= link_to 'Edit Homegroup', edit_homegroup_path(@homegroup) %> |
            <%= link_to 'Add New Item', new_homegroup_item_path(@homegroup) %>
</h2>


<table>
  <thead>
    <tr>
      <th>Items</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homegroup.items.each do |item| %>
      <tr>
        <td><%= item.item_name %></td>
        <td><%= link_to 'Edit', edit_homegroup_item_path(item) %></td>
        <td><%= button_to 'Remove from List', homegroup_item_url(@homegroup, item), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= form_for @invite, :url => invites_path do |f| %>
    <%= f.hidden_field :homegroup_id, :value => @homegroup.id %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.submit 'Send' %>
<% end %>

app/views/items/_form.html.erb
<%= form_for(@item, :url => homegroup_items_path(@homegroup)) do |f|%>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_name %>
    <%= f.text_field :item_name %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<% provide(:title, "Edit Item") %>

<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Item name</th>
      <th>Homegroup</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.item_name %></td>
        <td><%= item.homegroup_id %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<% provide(:title, "Add Item") %>

<h1>New Item</h1>

<%= render 'form', item: @item %>

<!-- %= link_to 'Back', items_path % -->

app/views/items/show.html.erb
<% provide(:title, "Item") %>

<p>
  <strong>Item name:</strong>
  <%= @item.item_name %>
</p>

<p>
  <strong>Homegroup:</strong>
  <%= @item.homegroup_id %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>

  </head>

  <body>
    <%= render 'layouts/header' %>


    <div class="container">
      <p id="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<div class="center jumbotron">
  <h1>Welcome to GroceryList</h1>

  <h1>
    About
  </h1>
  <p>
    GroceryList is cloud-sourced shopping list. Users can create a homegroup, add items
    to the list, and can share the list with multiple users by sending them an invitation
    from your homegroup.
  </p>

  <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>